/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_androidrecipes_ndkjni_NativeLib */

#ifndef _Included_com_androidrecipes_ndkjni_NativeLib
#define _Included_com_androidrecipes_ndkjni_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_androidrecipes_ndkjni_NativeLib
 * Method:    getCpuCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_androidrecipes_ndkjni_NativeLib_getCpuCount
  (JNIEnv *, jclass);

/*
 * Class:     com_androidrecipes_ndkjni_NativeLib
 * Method:    getCpuFamily
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_androidrecipes_ndkjni_NativeLib_getCpuFamily
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
